# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 19:41


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wom_pebbles', '0001_initial'),
        ('wom_tributary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wom_river', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceUserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_pub_date', models.DateTimeField(verbose_name=b'reference publication date')),
                ('has_been_read', models.BooleanField(default=False)),
                ('has_been_saved', models.BooleanField(default=False)),
                ('main_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wom_pebbles.Reference')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wom_pebbles.Reference')),
            ],
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(verbose_name=b'saved date')),
                ('is_public', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default=b'')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wom_pebbles.Reference')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_feeds', models.ManyToManyField(related_name='userprofile', to='wom_tributary.GeneratedFeed')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('public_sources', models.ManyToManyField(related_name='publicly_related_userprofile', to='wom_pebbles.Reference')),
                ('sources', models.ManyToManyField(related_name='userprofile', to='wom_pebbles.Reference')),
                ('twitter_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='wom_tributary.TwitterUserInfo')),
                ('web_feeds', models.ManyToManyField(to='wom_river.WebFeed')),
            ],
        ),
    ]
