# Generated by Django 2.2.20 on 2021-04-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom_river', '0004_webfeedcollation'),
        ('wom_user', '0002_auto_20190531_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='collating_feeds',
            field=models.ManyToManyField(to='wom_river.WebFeedCollation'),
        ),
    ]
