# Generated by Django 5.2.12 on 2026-06-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wom_user', '0003_userprofile_collating_feeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_info',
        ),
    ]
