# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 19:41


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wom_pebbles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[(b'TWTR', b'twitter')], default=b'TWTR', max_length=4)),
                ('title', models.CharField(max_length=50)),
                ('last_update_check', models.DateTimeField(verbose_name=b'last update')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wom_pebbles.Reference')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('generated_feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wom_tributary.GeneratedFeed')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('oauth_access_token', models.TextField()),
                ('oauth_access_token_secret', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='twittertimeline',
            name='twitter_user_access_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wom_tributary.TwitterUserInfo'),
        ),
    ]
