# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom_tributary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedfeed',
            name='last_update_check',
            field=models.DateTimeField(verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='generatedfeed',
            name='provider',
            field=models.CharField(choices=[('TWTR', 'twitter')], default='TWTR', max_length=4),
        ),
    ]
