# Generated by Django 2.2.28 on 2023-01-28 15:49

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wom_tributary', '0003_generatedfeed_item_relevance_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastodonApplicationRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_url', models.CharField(max_length=255)),
                ('application_name', models.CharField(max_length=255)),
                ('redirect_uri', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=257)),
                ('client_secret', django_cryptography.fields.encrypt(models.CharField(max_length=257))),
                ('validation_key', models.CharField(max_length=257)),
            ],
        ),
        migrations.AlterField(
            model_name='generatedfeed',
            name='provider',
            field=models.CharField(choices=[('TWTR', 'twitter'), ('MSTO', 'mastodon')], default='TWTR', max_length=4),
        ),
        migrations.CreateModel(
            name='MastodonUserAccessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_access_token', models.TextField()),
                ('application_registration_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wom_tributary.MastodonApplicationRegistration')),
            ],
        ),
        migrations.CreateModel(
            name='MastodonTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wom_tributary.GeneratedFeed')),
                ('mastodon_user_access_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wom_tributary.MastodonUserAccessInfo')),
            ],
        ),
    ]
