# Generated by Django 5.2.12 on 2026-06-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom_tributary', '0004_auto_20230128_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedfeed',
            name='provider',
            field=models.CharField(choices=[('MSTO', 'mastodon')], default='MSTO', max_length=4),
        ),
        migrations.DeleteModel(
            name='TwitterTimeline',
        ),
        migrations.DeleteModel(
            name='TwitterUserInfo',
        ),
    ]
