# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wom_pebbles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmlURL', models.CharField(max_length=255)),
                ('last_update_check', models.DateTimeField(verbose_name=b'last update')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wom_pebbles.Reference')),
            ],
        ),
    ]
