# Generated by Django 2.2.19 on 2021-04-02 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom_river', '0002_auto_20190531_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='webfeed',
            name='item_relevance_duration',
            field=models.DurationField(default=datetime.timedelta(days=28)),
        ),
    ]
