# Generated by Django 2.2.20 on 2021-04-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wom_pebbles', '0002_auto_20190531_2338'),
        ('wom_river', '0003_webfeed_item_relevance_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebFeedCollation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_completed_collation_date', models.DateTimeField(verbose_name='latest collation date')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wom_river.WebFeed')),
                ('references', models.ManyToManyField(to='wom_pebbles.Reference')),
            ],
        ),
    ]
