# Generated by Django 2.2.20 on 2021-05-14 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wom_river', '0004_webfeedcollation'),
    ]

    operations = [
        migrations.AddField(
            model_name='webfeedcollation',
            name='latest_reference_flushed',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='latest reference flushed'),
        ),
    ]
