# Generated by Django 5.2.12 on 2026-04-03 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom_river', '0005_webfeedcollation_latest_reference_flushed'),
    ]

    operations = [
        migrations.AddField(
            model_name='webfeed',
            name='permanent_failure_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webfeed',
            name='permanent_failure_diagnotic',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='webfeed',
            name='permanent_failure_last_detection_date',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
