# Generated by Django 5.2.12 on 2026-04-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom_river', '0006_webfeed_permanent_failure_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webfeed',
            name='last_update_failed',
            field=models.BooleanField(default=False),
        ),
    ]
