# Generated by Django 5.2.12 on 2026-04-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wom_river', '0007_webfeed_last_update_failed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webfeed',
            old_name='permanent_failure_diagnotic',
            new_name='permanent_failure_diagnostic',
        ),
    ]
