# Generated by Django 5.2.12 on 2026-08-16 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom_river', '0008_rename_permanent_failure_diagnotic_webfeed_permanent_failure_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='webfeed',
            name='latest_update_failure_start_date',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
